/**
 * Reading an author's Dockerfile well enough to build it where it expects.
 *
 * The pipeline used to answer two questions by assumption. "Is there a
 * Dockerfile here" was asked for the primary and never for a sibling — the
 * sibling path OVERWROTE whatever was in the directory with a generated file.
 * And "where does it build from" was always answered `the service's own
 * directory`.
 *
 * Both were wrong for the same repository, and it is not an unusual one. The
 * full-stack FastAPI template keeps `backend/Dockerfile`, and that file starts
 * by copying `./frontend` and building it, so the API image contains the web
 * assets it serves. Its own compose file says so in as many words:
 *
 *   build:
 *     context: .
 *     dockerfile: backend/Dockerfile
 *
 * Deployed as two services from two directories, the generated backend image had
 * no frontend in it and the app died on import with `Frontend directory
 * '/app/app/frontend' does not exist`. The build passed. The deploy then blamed
 * $PORT and missing secrets, because that is what the failure looks like from
 * outside a container that never finished importing.
 *
 * Everything here is pure and takes the file's text, so the rules can be checked
 * against real Dockerfiles without a build.
 */

/** One source path a Dockerfile copies in from the build context. */
export interface CopySource {
  path: string;
  /** The line it came from, for messages that have to be believable. */
  line: number;
}

/**
 * Every path a Dockerfile reads FROM THE CONTEXT.
 *
 * `--from=` is skipped deliberately: `COPY --from=build /opt/app /app` reads
 * another stage's filesystem, not the context, and counting it would make almost
 * every multi-stage build look like it reaches outside its directory.
 *
 * The last argument of a COPY is the destination and is never a context path.
 * Flags are dropped, quotes are stripped, and the JSON array form is handled —
 * `COPY ["src", "dst"]` is legal and appears in generated files.
 */
export function copySources(dockerfile: string): CopySource[] {
  const out: CopySource[] = [];
  const lines = dockerfile.split(/\r?\n/);

  for (let i = 0; i < lines.length; i++) {
    // A backslash continues an instruction onto the next line, and a COPY split
    // that way is still one COPY. Joined before parsing rather than after,
    // because the destination is only the last argument of the WHOLE thing.
    let raw = lines[i];
    let last = i;
    while (/\\\s*$/.test(raw) && last + 1 < lines.length) {
      last++;
      raw = raw.replace(/\\\s*$/, " ") + lines[last];
    }
    const started = i;
    i = last;

    const m = /^\s*(COPY|ADD)\s+(.*)$/i.exec(raw);
    if (!m) continue;
    let rest = m[2].trim();
    if (rest.startsWith("#")) continue;

    // `--from=build`, `--chown=1000:1000`, `--chmod=755`. A --from means the
    // source is a stage, not the context, so the whole instruction is skipped.
    let fromStage = false;
    while (rest.startsWith("--")) {
      const flag = rest.slice(0, rest.search(/\s/) < 0 ? rest.length : rest.search(/\s/));
      if (/^--from=/i.test(flag)) fromStage = true;
      rest = rest.slice(flag.length).trim();
    }
    if (fromStage || !rest) continue;

    let args: string[];
    if (rest.startsWith("[")) {
      try {
        const parsed: unknown = JSON.parse(rest);
        args = Array.isArray(parsed) ? parsed.map(String) : [];
      } catch {
        continue;
      }
    } else {
      args = rest.split(/\s+/).filter(Boolean).map((a) => a.replace(/^["']|["']$/g, ""));
    }
    // One argument is a malformed COPY; two or more means the last is where it
    // lands. Either way the destination is not a context path.
    if (args.length < 2) continue;
    for (const src of args.slice(0, -1)) {
      // A build argument in a path is not something to resolve — `COPY
      // ${SRC}/app .` names nothing until the build runs.
      if (src.includes("$")) continue;
      out.push({ path: src, line: started + 1 });
    }
  }
  return out;
}

/**
 * Does this Dockerfile expect to be built from the REPOSITORY, not its own
 * directory?
 *
 * `serviceDirEntries` and `repoRootEntries` are the names present in each place;
 * passing them rather than reading the disk is what keeps this checkable.
 *
 * The rule is deliberately about EVIDENCE, not cleverness. A path that climbs
 * out with `../` says so outright. Otherwise a source is only taken as proof
 * when it is missing beside the Dockerfile and present at the repository root —
 * anything else could be produced by an earlier stage, generated by a RUN, or
 * simply be a file the author knows about and we do not.
 */
export function wantsRepoRootContext(
  dockerfile: string,
  serviceDirEntries: string[],
  repoRootEntries: string[],
): boolean {
  const inDir = new Set(serviceDirEntries);
  const atRoot = new Set(repoRootEntries);

  for (const { path } of copySources(dockerfile)) {
    const clean = path.replace(/^\.\//, "").replace(/\/+$/, "");
    if (clean === "." || clean === "") continue;
    if (clean.startsWith("../")) return true;
    const head = clean.split("/")[0];
    // A wildcard names a shape, not a file, and cannot be looked up.
    if (head.includes("*") || head.includes("?")) continue;
    if (!inDir.has(head) && atRoot.has(head)) return true;
  }
  return false;
}

/**
 * Is this repository ONE service that its own Dockerfile already assembles?
 *
 * Asked before the repo is split into a frontend and an API, because a
 * Dockerfile in one candidate that copies another candidate's directory is the
 * author saying those are not two deployments. Splitting anyway produces two
 * images, one of which is missing the half it was told to serve.
 *
 * Returns the directory that owns the build, or null when nothing claims the
 * others — in which case the split stands.
 */
export function buildOwner(
  candidates: { dir: string; dockerfile?: string }[],
): string | null {
  const dirs = candidates.map((c) => c.dir.replace(/^\.\//, "").replace(/\/+$/, "")).filter((d) => d && d !== ".");
  for (const c of candidates) {
    if (!c.dockerfile) continue;
    const mine = c.dir.replace(/^\.\//, "").replace(/\/+$/, "");
    for (const { path } of copySources(c.dockerfile)) {
      const head = path.replace(/^\.\//, "").split("/")[0];
      if (head && head !== mine && dirs.includes(head)) return c.dir;
    }
  }
  return null;
}
