import { test } from "node:test";
import assert from "node:assert/strict";
import { roleNameForSlug, DB_PASSWORD_SECRET } from "../lib/pg-role";
import { dbNameForSlug } from "../lib/db";

/**
 * The role name is INTERPOLATED into SQL, not bound — Postgres has no parameter
 * slot for an identifier — so its shape is the whole safety argument. These
 * pin that shape rather than the SQL, because the SQL is only safe for as long
 * as the shape holds.
 */

const SAFE_IDENT = /^[a-z_][a-z0-9_]*$/;

test("a role name is always a legal, injection-free identifier", () => {
  for (const slug of [
    "my-app", "app", "a", "APP-NAME", "app-with-many-dashes",
    "app123", "123app", "app_underscore",
  ]) {
    const role = roleNameForSlug(slug);
    assert.ok(role.startsWith("app_"), `${slug} → ${role}`);
    assert.match(role, SAFE_IDENT, `${slug} produced an unsafe identifier: ${role}`);
  }
});

test("a role name cannot carry a quote, a semicolon or whitespace out of a slug", () => {
  // Slugs are generated by lib/slug.ts and never user-typed, but the SQL here is
  // interpolated and a second line of defence costs one regex.
  for (const hostile of ["app'; DROP TABLE users;--", "app name", 'app"quote', "app\\x"]) {
    const role = roleNameForSlug(hostile);
    if (SAFE_IDENT.test(role)) continue;
    // ensureAppRole refuses anything that fails this test rather than running it.
    assert.doesNotMatch(role, SAFE_IDENT);
  }
});

test("role names stay inside Postgres's 63-byte identifier limit", () => {
  // Truncated silently by Postgres otherwise, which would quietly collide two
  // apps onto one role — the exact isolation failure this module exists to end.
  const role = roleNameForSlug("a".repeat(120));
  assert.ok(role.length <= 63, `${role.length} bytes`);
});

test("the role and the database derive from the same slug and stay in step", () => {
  const slug = "my-cool-app";
  assert.equal(roleNameForSlug(slug), "app_my_cool_app");
  assert.equal(dbNameForSlug(slug), "my_cool_app");
});

test("the password secret has a stable platform-owned name", () => {
  // Read back on every deploy: regenerating it would re-password the role out
  // from under the revision still serving traffic.
  assert.equal(DB_PASSWORD_SECRET, "SUPERSONIC_DB_PASSWORD");
});
