#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
TOTAL_MINUTES=40

NEW_DOMAIN="thebay.cloud"
OLD_DOMAIN="supersonic.cv"
GCP_PROJECT="supersonic-deploy-prod"
GCP_REGION="us-central1"
GCLOUD_ACCOUNT="a@supersonic.cv"
LB_IP="8.233.7.157"
# The four addresses a Cloud Run domain mapping answers on. Same set for every
# project; copied from what supersonic.cv already resolves to.
RUN_APEX_IPS="216.239.32.21 216.239.34.21 216.239.36.21 216.239.38.21"
DNS_AUTH="bay-dns-auth"
CERT_NAME="bay-wildcard"
CERT_MAP="supersonic-cert-map"

# ── Helpers ───────────────────────────────────────────────────────────────

# resolved HOST TYPE — what DNS actually answers, through a public resolver
# rather than whatever this machine caches.
resolved() { dig +short "$2" "$1" @1.1.1.1 2>/dev/null | tr '\n' ' ' | sed 's/ *$//'; }

# await_dns HOST TYPE EXPECT_SUBSTRING MINUTES — poll until DNS agrees, or give
# up and say so. Namecheap is usually seconds and occasionally an hour; the
# difference is invisible from here and the wizard should not pretend otherwise.
await_dns() {
  local host="$1" type="$2" want="$3" mins="${4:-10}" tries=$(( ${4:-10} * 4 )) got=""
  say "waiting for $host ($type) to answer with $want — up to ${mins} min"
  for _ in $(seq 1 "$tries"); do
    got="$(resolved "$host" "$type")"
    if [[ "$got" == *"$want"* ]]; then
      printf '  %s✓%s %s → %s\n' "$GREEN" "$RESET" "$host" "$got"
      return 0
    fi
    sleep 15
  done
  warn "$host still answers: ${got:-nothing}"
  note "DNS can take an hour. Re-run this wizard later; every step is idempotent."
  return 1
}

banner "Bay — put thebay.cloud beside supersonic.cv"

# ──────────────────────────────────────────────────────────────────────────
stage "Preflight" 2
say "Nothing is created in this stage."
for t in gcloud dig curl; do command -v "$t" >/dev/null 2>&1 || { warn "missing: $t"; exit 1; }; done
ACCOUNT="$(gcloud config get-value account 2>/dev/null || true)"
if [[ "$ACCOUNT" != "$GCLOUD_ACCOUNT" ]]; then
  warn "gcloud is $ACCOUNT, expected $GCLOUD_ACCOUNT"
  note "  gcloud auth login $GCLOUD_ACCOUNT   # with the account named"
  exit 1
fi
say "gcloud account: $ACCOUNT ✓"
say "old domain still serving: $(resolved "app.$OLD_DOMAIN" A)"
say "new domain answers with:  $(resolved "$NEW_DOMAIN" A)"
note "That last one is Namecheap's parking page until stage 3."
pause "Ready?"

# ──────────────────────────────────────────────────────────────────────────
stage "Namecheap — the certificate challenge" 6
say "A wildcard certificate cannot be authorized by the load balancer, so"
say "Google proves ownership through DNS instead. One CNAME, added once."
printf '\n'
open_url "https://ap.www.namecheap.com/domains/domaincontrolpanel/${NEW_DOMAIN}/advancedns"
step "Advanced DNS → Add New Record → CNAME Record"
printf '\n'
CHALLENGE="$(gcloud certificate-manager dns-authorizations describe "$DNS_AUTH" \
  --project="$GCP_PROJECT" --format='value(dnsResourceRecord.data)' 2>/dev/null)"
printf '  %sHost%s   _acme-challenge\n' "$BOLD" "$RESET"
printf '  %sValue%s  %s\n' "$BOLD" "$RESET" "${CHALLENGE:-<run: gcloud certificate-manager dns-authorizations describe $DNS_AUTH>}"
printf '  %sTTL%s    Automatic\n\n' "$BOLD" "$RESET"
warn "Namecheap appends the domain itself — enter the Host as _acme-challenge, not the full name."
pause "Added?"
await_dns "_acme-challenge.$NEW_DOMAIN" CNAME "authorize.certificatemanager.goog" 10 || true

# ──────────────────────────────────────────────────────────────────────────
stage "Namecheap — where the four addresses point" 8
say "Four records. They mirror exactly what $OLD_DOMAIN has today."
printf '\n'
step "A Record      @      216.239.32.21"
step "A Record      @      216.239.34.21"
step "A Record      @      216.239.36.21"
step "A Record      @      216.239.38.21"
note "  The apex. These four are Google's addresses for a Cloud Run domain"
note "  mapping — the landing site answers there."
printf '\n'
step "CNAME Record  www    ghs.googlehosted.com."
step "CNAME Record  app    ghs.googlehosted.com."
note "  The dashboard and the API."
printf '\n'
step "A Record      *      $LB_IP"
note "  Every app's own address. This one goes to the load balancer, not to"
note "  Cloud Run: it is the edge proxy that turns <slug>.$NEW_DOMAIN into an app."
printf '\n'
warn "Delete Namecheap's default parking records (URL Redirect / CNAME www) first,"
warn "or they will fight the ones above."
pause "All seven added?"
await_dns "$NEW_DOMAIN" A "216.239" 10 || true
await_dns "test.$NEW_DOMAIN" A "$LB_IP" 10 || true

# ──────────────────────────────────────────────────────────────────────────
stage "The wildcard certificate" 5
say "Created now, issued by Google on its own clock once the challenge above"
say "is visible. Idempotent — re-running this wizard will not duplicate it."
if gcloud certificate-manager certificates describe "$CERT_NAME" --project="$GCP_PROJECT" >/dev/null 2>&1; then
  say "already exists"
else
  gcloud certificate-manager certificates create "$CERT_NAME" \
    --domains="*.$NEW_DOMAIN" \
    --dns-authorizations="$DNS_AUTH" \
    --project="$GCP_PROJECT" >/dev/null 2>&1 \
    && printf '  %s✓ created%s %s\n' "$GREEN" "$RESET" "$CERT_NAME" \
    || { warn "creation failed"; SKIPPED+=("certificate $CERT_NAME"); }
fi
STATE="$(gcloud certificate-manager certificates describe "$CERT_NAME" \
  --project="$GCP_PROJECT" --format='value(managed.state)' 2>/dev/null)"
say "state: ${STATE:-unknown}"
if [[ "$STATE" != "ACTIVE" ]]; then
  note "PROVISIONING is normal and can take up to an hour. Nothing below depends"
  note "on it finishing, and re-running this wizard later will show ACTIVE."
fi
pause "Press Enter."

# ──────────────────────────────────────────────────────────────────────────
stage "The certificate map" 3
say "The map is what the load balancer reads. One entry per hostname pattern;"
say "$OLD_DOMAIN keeps its own and is not touched."
if gcloud certificate-manager maps entries describe bay-wildcard \
     --map="$CERT_MAP" --project="$GCP_PROJECT" >/dev/null 2>&1; then
  say "entry already exists"
else
  gcloud certificate-manager maps entries create bay-wildcard \
    --map="$CERT_MAP" --hostname="*.$NEW_DOMAIN" --certificates="$CERT_NAME" \
    --project="$GCP_PROJECT" >/dev/null 2>&1 \
    && printf '  %s✓ created%s map entry for *.%s\n' "$GREEN" "$RESET" "$NEW_DOMAIN" \
    || { warn "map entry failed — usually means the certificate is not ACTIVE yet"; SKIPPED+=("cert map entry for *.$NEW_DOMAIN"); }
fi
pause "Press Enter."

# ──────────────────────────────────────────────────────────────────────────
stage "Verify the domain with Google" 6
say "Cloud Run will not map a hostname on a domain nobody has proved they own."
say "This is Search Console, and it is a different proof from stage 2's."
printf '\n'
if gcloud domains list-user-verified --project="$GCP_PROJECT" 2>/dev/null | grep -qx "$NEW_DOMAIN"; then
  say "$NEW_DOMAIN is already verified ✓"
else
  open_url "https://search.google.com/search-console/welcome"
  step "Choose 'Domain' (the left box), enter: $NEW_DOMAIN"
  step "Google shows a TXT record. Add it in Namecheap: Host @, the value it gives."
  step "Come back to Search Console and press Verify."
  note "  Sign in as $GCLOUD_ACCOUNT — verification is attached to the account,"
  note "  and one done under a personal login is invisible to this project."
  pause "Verified?"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Map the three hostnames" 6
say "apex and www to the landing site, app to the control plane — the same"
say "three $OLD_DOMAIN has."
for pair in "$NEW_DOMAIN:supersonic-landing" "www.$NEW_DOMAIN:supersonic-landing" "app.$NEW_DOMAIN:supersonic-control-plane"; do
  host="${pair%%:*}"; svc="${pair##*:}"
  printf '  %-24s → %-26s ' "$host" "$svc"
  if gcloud beta run domain-mappings describe --domain="$host" \
       --region="$GCP_REGION" --project="$GCP_PROJECT" >/dev/null 2>&1; then
    printf '%salready mapped%s\n' "$DIM" "$RESET"
  elif gcloud beta run domain-mappings create --service="$svc" --domain="$host" \
       --region="$GCP_REGION" --project="$GCP_PROJECT" >/dev/null 2>&1; then
    printf '%s✓%s\n' "$GREEN" "$RESET"
  else
    printf '%s✗%s\n' "$RED" "$RESET"
    SKIPPED+=("domain mapping $host → $svc")
  fi
done
note "Cloud Run issues its own certificate for these three. Minutes, sometimes"
note "longer, and independent of the wildcard above."
pause "Press Enter."

# ──────────────────────────────────────────────────────────────────────────
stage "Serve both roots, and check" 4
say "The edge decides which app a hostname means. Until it is told about the"
say "new root, $NEW_DOMAIN resolves here and answers 404."
printf '\n'
warn "This updates a live service. --update-env-vars, never --set-env-vars:"
warn "the latter REPLACES the whole list and has wiped a service before."
printf '\n'
if confirm "Tell the proxy to serve both roots now?"; then
  # ROOT_DOMAIN stays the OLD domain here on purpose. This stage makes the new
  # domain WORK; it does not make it canonical. Flipping what the platform calls
  # itself is the cutover, and it is a separate decision on a separate day.
  gcloud run services update supersonic-proxy \
    --region="$GCP_REGION" --project="$GCP_PROJECT" \
    --update-env-vars="LEGACY_ROOT_DOMAINS=$NEW_DOMAIN" --quiet >/dev/null 2>&1 \
    && printf '  %s✓%s supersonic-proxy now serves both\n' "$GREEN" "$RESET" \
    || { warn "update failed"; SKIPPED+=("LEGACY_ROOT_DOMAINS on supersonic-proxy"); }
else
  SKIPPED+=("LEGACY_ROOT_DOMAINS on supersonic-proxy")
fi
printf '\n'
say "What answers now:"
for h in "$NEW_DOMAIN" "app.$NEW_DOMAIN" "l3sgp.$NEW_DOMAIN" "l3sgp.$OLD_DOMAIN"; do
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "https://$h/" 2>/dev/null || echo "---")"
  printf '  %-28s %s\n' "$h" "$code"
done
note "A 000 or --- means the certificate has not finished. Re-run to re-check."
pause "Press Enter."

finish
