#!/usr/bin/env bash
#
# The cutover. Moves live Cloud Run apps onto the fleet, one at a time, and only
# flips an app's traffic after that app has answered from the fleet.
#
# The order is the whole safety property:
#
#   1. place        — the node starts the app; nobody is routed to it yet
#   2. verify       — ask the node's router for it directly, over the LB
#   3. flip         — only now does apps.run_url point at the fleet
#
# A failure at 1 or 2 leaves the app exactly where it was, still served by Cloud
# Run, and costs nothing but a stopped sandbox. `fleetctl.sh unplace <slug>` is
# the reverse gear at any point after.
#
# Usage:  sudo -E bash migrate.sh <slugs-file> [max]
set -uo pipefail

PROJECT=supersonic-deploy-prod
REPO="us-central1-docker.pkg.dev/${PROJECT}/cloud-run-source-deploy"
LB="${FLEET_LB:-8.232.255.172}"
NODE="${FLEET_NODE:-fleet-lab-1}"
LIST="${1:?usage: migrate.sh <slugs-file> [max]}"
MAX="${2:-999}"

export PGHOST=127.0.0.1 PGPORT=5432 PGUSER=postgres PGDATABASE=supersonic_platform
q() { psql -qtA -c "$1"; }

ok=0; skipped=0; failed=0
i=0
while read -r SLUG; do
  [ -z "$SLUG" ] && continue
  i=$((i+1)); [ "$i" -gt "$MAX" ] && break

  RUNTIME=$(q "SELECT runtime FROM apps WHERE slug='$SLUG'")
  if [ "$RUNTIME" = "fleet" ]; then
    echo "· $SLUG already on the fleet"; skipped=$((skipped+1)); continue
  fi

  # Remember where it was. This is what makes the flip reversible without
  # guessing — a Cloud Run URL is not reconstructable from the slug.
  OLD_URL=$(q "SELECT coalesce(run_url,'') FROM apps WHERE slug='$SLUG'")
  if [ -z "$OLD_URL" ]; then
    echo "· $SLUG has no run_url (never went live) — skipping"; skipped=$((skipped+1)); continue
  fi

  IMAGE="${REPO}/${SLUG}:latest"
  SPEC=$(printf '{"slug":"%s","image":"%s","port":8080,"memoryBytes":2147483648,"cpuShares":1024,"healthPath":"/"}' "$SLUG" "$IMAGE")

  # 1. place
  q "INSERT INTO fleet_placements(slug,node,spec) VALUES('$SLUG','$NODE','$SPEC'::jsonb)
     ON CONFLICT (slug,node) DO UPDATE SET spec=EXCLUDED.spec, placed_at=now()" >/dev/null
  q "UPDATE apps SET runtime='fleet' WHERE slug='$SLUG'" >/dev/null

  # 2. verify — through the load balancer, addressed the way the proxy will
  #    address it. Not through localhost: the point is to exercise the path
  #    real traffic will take, LB included.
  code=000; fromRouter=x
  for _ in $(seq 1 24); do
    sleep 5
    # -D captures headers: the router marks its OWN responses with
    # X-Supersonic-Router, and a routing miss returns 404 exactly like an app
    # whose root path is undefined. Without reading that header this check
    # passes an app that is not running at all.
    code=$(curl -s -m 10 -o /dev/null -D /tmp/mig.hdr -w '%{http_code}' \
             -H "x-supersonic-slug: $SLUG" "http://${LB}/" 2>/dev/null || echo 000)
    fromRouter=$(grep -i '^x-supersonic-router:' /tmp/mig.hdr 2>/dev/null | tr -d '\r' | awk '{print $2}')
    # <500 AND generated by the app, not by the router. An app that redirects to
    # /login or 404s its root is working; a router miss is not.
    [ "$code" != "000" ] && [ "$code" -lt 500 ] && [ -z "$fromRouter" ] && break
  done

  if [ "$code" = "000" ] || [ "$code" -ge 500 ] || [ -n "$fromRouter" ]; then
    [ -n "$fromRouter" ] && echo "   (router said: $fromRouter — the app never came up here)"
    echo "✗ $SLUG did not answer from the fleet (last $code) — rolling back, still on Cloud Run"
    q "UPDATE apps SET runtime='cloudrun' WHERE slug='$SLUG'" >/dev/null
    q "DELETE FROM fleet_placements WHERE slug='$SLUG'" >/dev/null
    failed=$((failed+1))
    continue
  fi

  # 3. flip. The edge proxy needs no change: it already forwards
  #    x-supersonic-slug, which is how the shared static server has always
  #    worked, and the fleet router reads the same header.
  q "UPDATE apps SET run_url='http://${LB}' WHERE slug='$SLUG'" >/dev/null
  echo "✓ $SLUG on the fleet (was $OLD_URL, answered $code)"
  ok=$((ok+1))
done < "$LIST"

echo
echo "migrated $ok · skipped $skipped · failed $failed"
